# Generated by Django 4.0.3 on 2022-04-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_author_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
